version: 2

models:
  - name: prices_latest
    description: This model contains the most recent price for each item.
    columns:
      - name: id
        description: The id of the item.
        tests:
          - not_null
          - relationships:
              field: id
              to: source("bronze", env_var('DBT_BQ_TABLE_ITEMS'))
      - name: price
        description: The most recent price of the item.
      - name: name
        description: The name of the item.
      - name: description
        description: The description of the item.
      - name: recorded_at
        description: The datetime of the record.

  - name: prices_daily
    description: This model contains daily min, max, and average prices for each item.
    columns:
      - name: id
        description: The id of the item.
        tests:
          - not_null
          - relationships:
              field: id
              to: source("bronze", env_var('DBT_BQ_TABLE_ITEMS'))
      - name: name
        description: The name of the item.
      - name: description
        description: The description of the item.
      - name: min_price
        description: The minimum price of the item on the record's date.
      - name: max_price
        description: The maximum price of the item on the record's date.
      - name: avg_price
        description: The average price of the item on the record's date.
      - name: recorded_date
        description: The date of the record.

  - name: prices_weekly
    description: This model contains weekly min, max, and average prices for each item.
    columns:
      - name: id
        description: The id of the item.
        tests:
          - not_null
          - relationships:
              field: id
              to: source("bronze", env_var('DBT_BQ_TABLE_ITEMS'))
      - name: name
        description: The name of the item.
      - name: description
        description: The description of the item.
      - name: min_price
        description: The minimum price of the item over the time period.
      - name: max_price
        description: The maximum price of the item over the time period.
      - name: avg_price
        description: The average price of the item over the time period.

  - name: prices_all_time
    description: This model contains all time min, max, and average prices for each item.
    columns:
      - name: id
        description: The id of the item.
        tests:
          - not_null
          - relationships:
              field: id
              to: source("bronze", env_var('DBT_BQ_TABLE_ITEMS'))
      - name: name
        description: The name of the item.
      - name: description
        description: The description of the item.
      - name: min_price
        description: The minimum price of the item over the time period.
      - name: max_price
        description: The maximum price of the item over the time period.
      - name: avg_price
        description: The average price of the item over the time period.
